In [215]:
import pandas as pd
import numpy as np
import pyproj
import folium
import os
os.environ["PATH"] += os.pathsep + "."

In [2]:
data = pd.read_csv("data.csv")

In [130]:
lat_lon = pd.read_csv("lat_lon.csv")[["lat", "lon"]]

In [131]:
lat_lon

             lat        lon
0     -73.977946  40.722732
1     -73.981031  40.721552
2     -73.979864  40.726498
3     -73.979857  40.726569
4     -73.984223  40.724240
5     -73.980524  40.728496
6     -73.979394  40.729690
7     -73.975629  40.724702
8     -73.977270  40.726709
9     -73.978423  40.720893
10    -73.978798  40.721151
11    -73.978953  40.721217
12    -73.977788  40.722625
13    -73.978783  40.723737
14    -73.978061  40.723506
15    -73.977870  40.723426
16    -73.977217  40.723629
17    -73.981055  40.724860
18    -73.980208  40.724415
19    -73.980128  40.724382
20    -73.980287  40.724154
21    -73.980688  40.724324
22    -73.979342  40.724524
23    -73.980125  40.724859
24    -73.979374  40.725331
25    -73.980027  40.725600
26    -73.978079  40.725600
27    -73.977729  40.726069
28    -73.977797  40.727014
29    -73.976783  40.728589
...          ...        ...
60265 -74.212509  40.541066
60266 -74.215888  40.540266
60267 -74.218533  40.540332
60268 -74.219633  40.540199
60269 -74.221537  40.541337
60270 -74.221637  40.541315
60271 -74.219955  40.541757
60272 -74.220609  40.546836
60273 -74.222111  40.537603
60274 -74.219231  40.539233
60275 -74.222395  40.538788
60276 -74.222438  40.538555
60277 -74.221330  40.538606
60278 -74.221309  40.538845
60279 -74.221573  40.539358
60280 -74.220796  40.539425
60281 -74.223028  40.537574
60282 -74.223444  40.537090
60283 -74.222901  40.537102
60284 -74.222802  40.536800
60285 -74.222827  40.535438
60286 -74.220948  40.537355
60287 -74.222559  40.537127
60288 -74.221661  40.536454
60289 -74.221725  40.536250
60290 -74.222180  40.535747
60291 -74.220737  40.532291
60292 -74.222335  40.532631
60293 -74.219173  40.530351
60294 -74.217960  40.537937

[60295 rows x 2 columns]

In [143]:
data[["lon", "lat"]] = lat_lon

In [199]:
data["month"] = pd.to_datetime(data.sale_date).dt.month

In [205]:
circles = data.groupby("neighborhood")["lat", "lon"].mean()

In [206]:
counts = data.groupby("neighborhood").lat.count()
prices = data.groupby("neighborhood").sale_price.mean()

In [1]:
def plot_circles(data, attribute, func, constant=50):
    if func == "cnt":
        gb = data.groupby("neighborhood")[attribute].count()
    elif func == "mean":
        gb = data.groupby("neighborhood")[attribute].mean()
    max_val = gb.max()


    folium_map = folium.Map(location=[40.738, -73.98],
                            zoom_start=11,
                            tiles="CartoDB dark_matter")

    for (neigh, attr), lat, long in zip(gb.items(),  circles.lat[1:], circles.lon[1:]):
        radius = constant*np.sqrt(2)*(attr/max_val)
        marker = folium.CircleMarker(location=[lat, long], radius=radius, color='red')
        marker.add_to(folium_map)
    return folium_map
        
plot_circles(data, "lat", "cnt")

NameError: name 'data' is not defined